default:
  shortname: whitman-manuscripts
  collection: whitman
  site_url: https://whitmanarchive.org
  solr_core: api_whitman
  tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl

development:
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1
  site_url: https://whitman-dev.unl.edu
  solr_path: https://whitman-dev.unl.edu/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-manuscripts
    site_url: https://whitman-dev.unl.edu

production:
  site_url: https://whitmanarchive.org
  solr_path: https://whitman-prod.unl.edu/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitmanarchive.org
    slug: whitman-manuscripts

grant:
  # NOTE: different collection name!!!
  collection: whitman-grant
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1_grant
  site_url: https://whitmanarchive.org
