default:
  shortname: whitman-manuscripts
  collection: whitman-manuscripts
  solr_core: api_whitman
  tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl
 # allowed_files: config/allowed_files.txt
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  site_url: https://whitmanarchive.org
  media_base: https://whitmanarchive.org/media
  data_base: https://whitmanarchive.org/media
  variables_html:
    image_large: 1200
    image_thumb: 80
  api_version: "2.0"
  es_index: whitman-api_v2
  threads: 1

development:
  data_base: https://set_in_private_config/media
  media_base: https://set_in_private_config/media
  es_path: https://set_in_private_config/elastic
  site_url: https://set_in_private_config
  solr_path: https://set_in_private_config/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-manuscripts
    site_url: https://set_in_private_config

production:
  data_base: https://whitmanarchive.org/media
  site_url: https://whitmanarchive.org
  solr_path: https://set_in_private_config/solr
  allowed_files: config/allowed_files.txt

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitmanarchive.org
    slug: whitman-manuscripts
