default:
  # NOTE: options that apply to all the whitman data repos
  # are in data/config/private.yml
  # (solr_core, solr_path, solr_variables, etc)

  shortname: whitman-manuscripts
 collection: whitman
  site_url: https://whitmanarchive.org

  # TODO this collection_desc applies only to the subcategory and not the entire collection
  # collection_desc: Manuscripts for The Walt Whitman Archive

  tei_solr_xsl: collections/whitman-manuscripts/scripts/solr_transform_tei.xsl

  variables_solr:
    figures: false
    fw: false
    pb: false
    project: The_Walt_Whitman_Archive
    site_url: https://whitmanarchive.org
    slug: whitman-manuscripts
development:
  site_url: https://whitman-dev.unl.edu
  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitman-dev.unl.edu
    slug: whitman-manuscripts
# development:
  # development overrides here
# production:
  # production overrides here
